### ISSUE TITLE
NPE in UserGeneratedContentCleaner

### ISSUE THREAD

**Issue by rzasap** [wttech/CQ-Actions#17]
`19.02.2018 03:00:00.005 *ERROR* [sling-default-1859-com.cognifide.actions.msg.replication.cleaner.UserGeneratedContentCleaner.6063] org.apache.sling.commons.scheduler.impl.QuartzSche
duler Exception during job execution of com.cognifide.actions.msg.replication.cleaner.UserGeneratedContentCleaner@3e9dab48 : null
java.lang.NullPointerException: null
        at com.cognifide.actions.msg.replication.cleaner.UserGeneratedContentCleaner.removeNodesFromDayFolder(UserGeneratedContentCleaner.java:125)
        at com.cognifide.actions.msg.replication.cleaner.UserGeneratedContentCleaner.run(UserGeneratedContentCleaner.java:111)
        at org.apache.sling.commons.scheduler.impl.QuartzJobExecutor.execute(QuartzJobExecutor.java:118)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by devzbysiu** [comment]
This project is going to be archived. Closing
